services:
  reverse-proxy:
    image: nginx:1.29.2
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:Z,ro
      - nginx_logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:z,ro
      - ./certbot/conf/:/etc/nginx/ssl/:z,ro
      - wp_data:/var/www/html:ro
    networks:
      - proxy_net
      - frontend_net
    depends_on:
      - wordpress

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:z,rw
      - ./certbot/conf/:/etc/letsencrypt/:z,rw
    networks:
      - proxy_net

  wordpress:
    image: wordpress:php8.4-fpm
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: "${WP_DB_PASSWORD}"
      WORDPRESS_DB_NAME: wp_db
    volumes:
      - wp_data:/var/www/html
    networks:
      - frontend_net
      - db_net
    depends_on:
      - db

  db:
    image: mariadb:12.0.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: "${WP_DB_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db_net

networks:
  proxy_net:
    driver: bridge
    ipam:
      dns_nameservers:
        - 129.143.2.1
        - 129.143.2.4
        - 2001:7c0::53:1
        - 2001:7c0::53:4
  frontend_net:
    driver: bridge
    internal: true
    ipam:
      dns_nameservers:
        - 129.143.2.1
        - 129.143.2.4
        - 2001:7c0::53:1
        - 2001:7c0::53:4
  db_net:
    driver: bridge
    internal: true
    ipam:
      dns_nameservers:
        - 129.143.2.1
        - 129.143.2.4
        - 2001:7c0::53:1
        - 2001:7c0::53:4

volumes:
  db_data:
  nginx_logs:
  wp_data:
