services:
  reverse-proxy:
    image: nginx:1.29.2
    restart: always
    ports:
      - "80:80"
      - "[::]:80:80"
      - "443:443"
      - "[::]:443:443"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx_logs:/var/log/nginx
      - certbot_www:/var/www/certbot/:ro
      - certbot_conf:/etc/nginx/ssl/:ro
      - wp_data:/var/www/html:ro
    networks:
      - proxy_net
      - frontend_net
    depends_on:
      - wordpress

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot_www:/var/www/certbot/:rw
      - certbot_conf:/etc/letsencrypt/:rw
    networks:
      - proxy_net
  wordpress:
    image: wordpress:php8.4-fpm
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: "${WP_DB_PASSWORD}"
      WORDPRESS_DB_NAME: wp_db
    volumes:
      - wp_data:/var/www/html
    networks:
      - frontend_net
      - db_net
    depends_on:
      - db

  db:
    image: mariadb:12.0.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: "${WP_DB_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db_net

networks:
  proxy_net:
    driver: bridge
  frontend_net:
    driver: bridge
    internal: true
  db_net:
    driver: bridge
    internal: true

volumes:
  certbot_www:
  certbot_conf:
  db_data:
  nginx_logs:
  wp_data:
